- name: Remediate Windows vulnerabilities
  hosts: all
  gather_facts: no
  tasks:

    - name: Install all missing Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
