---
- name: Fix Windows vulnerabilities detected by Wazuh
  hosts: "{{ target_host }}"
  gather_facts: no

  tasks:
    - name: Install Security and Critical Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
        reboot_timeout: 3600
