---
- name: Fix Windows vulnerabilities detected by Wazuh
  hosts: all
  gather_facts: no

  tasks:

    - name: Install Windows Security & Critical Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
        reboot_timeout: 3600
